### ISSUE TITLE
undefined method `normalize' for Romaji:Module

### ISSUE THREAD

**Issue by atmarksharp** [makimoto/romaji#12]
I tried using this library like below.

```ruby
require "romaji/core_ext/string"

puts "tesuto".kana
```

but it raised `undefined method 'normalize' for Romaji:Module (NoMethodError).`

```
/user/.anyenv/envs/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/romaji-0.2.3/lib/romaji/string_extension.rb:6:in `normalize': undefined method `normalize' for Romaji:Module (NoMethodError)
	from /user/.anyenv/envs/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/romaji-0.2.3/lib/romaji/string_extension.rb:14:in `kana'
	from sample.rb:3:in `<main>'
```

The installation directory and the version of my ruby are below.

```bash
$ which ruby
/user/.anyenv/envs/rbenv/shims/ruby

$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by makimoto** [comment]
Thank you for your reporting.

`romaji/core_ext/string` is presupposed that `romaji` is required. So your code may work with adding `require "romaji"`.

I'll look into omitting `require "romaji"`on using only core_ext in future versions.

**Comment by atmarksharp** [comment]
@makimoto Adding `require "romaji"` before all, it worked! Thank you :)

My misreading of the README caused this trouble, sorry.
