### ISSUE TITLE
Release for PR #5 (duplicated hash key "n")

### ISSUE THREAD

**Issue by shuhei** [makimoto/romaji#6]
Any chance PR #5 is released anytime soon? I keep getting `warning: duplicated key at line 28 ignored: "n" ` on Ruby 2.2.0.

**Comment by makimoto** [comment]
done as romaji 0.2.2.
https://rubygems.org/gems/romaji/versions/0.2.2

thanks.

**Comment by shuhei** [comment]
Thanks for your quick response!

**Comment by seratch** [comment]
Thank you for your Incredibly quick response. :bow: 

I'm sorry for duplicated ping from @shuhei and me. We're working on same project which heavily uses romaji gem. Thanks a lot for your great gem!  :+1:

**Comment by makimoto** [comment]
np :innocent: 
thank you for telling me about it!
